[package]
name = "dongler-node"
version = "0.3.7"
edition = "2021"
license = "MIT"
authors = ["Daniel Fat"]
description = "Node.js bindings for fast Rust-native PDF and document extraction."
repository = "https://github.com/cristianexer/dongler"
publish = false

[lib]
name = "dongler_node"
crate-type = ["cdylib"]

[dependencies]
dongler-core = { path = "../dongler-core", version = "0.3.7" }
napi = { version = "3", default-features = false, features = ["napi8"] }
napi-derive = "3"
serde_json = "1.0"

[build-dependencies]
napi-build = "2"
